### ISSUE TITLE
pb avec la récupération de commentaire

### ISSUE THREAD

**Issue by quidoz** [equinton/dbstructure#1]
Bonjour

J'ai testé ce programme php. Ca marche pour 95% (voir plus des cas), mais je ne comprend pas pourquoi dans cette table (cf poisson.espece) il me ressort bien le commentaire sur la table et pas le commentaire sur l'attribut cd_nom - pourtant ca marche sur la table messure (cf copie d'ecran)

![image](https://user-images.githubusercontent.com/29607993/78878786-3e0af080-7a53-11ea-8da3-3ccf188067f0.png)

-- Table: poisson.espece

CREATE TABLE poisson.espece
(
    cd_nom integer NOT NULL,
    nom_scientifique character varying COLLATE pg_catalog."default",
    nom_vernaculaire character varying COLLATE pg_catalog."default",
    famille character varying COLLATE pg_catalog."default",
    CONSTRAINT pk_espece PRIMARY KEY (cd_nom)
);

ALTER TABLE poisson.espece OWNER to createur_savoie;
GRANT ALL ON TABLE poisson.espece TO createur_savoie;
GRANT SELECT ON TABLE poisson.espece TO lecteur_savoie;

COMMENT ON TABLE poisson.espece
    IS 'Liste les especes qui sont utiles dans ce domaine d''application. 
A noter : il faut éviter de refaire une table de taxonomie et préférer référencer les dictionnaires existants (TAXREF, WORWS, etc.) 
par leur identifiant (CD_NOM, APHIA_ID, etc.), et ne conserver que le strictement utile à l''application';

COMMENT ON COLUMN poisson.espece.cd_nom
    IS 'Identifiant unique de l''espèce dans le dictionnaire TAXREF';

**Comment by equinton** [comment]
Est-ce que tu as testé avec la version actuelle ? Il y a eu des modifs depuis la première version.

Sinon, essaie d'exécuter ce script (c'est celui qui est exécuté, modifié à la marge pour intégrer manuellement le nom du schéma et de la table) :
with req as
        (SELECT DISTINCT on (schemaname, tablename, field) schemaname, pg_tables.tablename,
           attnum,  pg_attribute.attname AS field,
            format_type(pg_attribute.atttypid,NULL) AS "type",
         (SELECT col_description(pg_attribute.attrelid,pg_attribute.attnum)) AS COMMENT,
         CASE pg_attribute.attnotnull
            WHEN FALSE THEN 0
           ELSE 1
         END AS "notnull",
         pg_constraint.conname AS "key",
         pc2.conname AS ckey,
         (SELECT pg_attrdef.adsrc
          FROM pg_attrdef
          WHERE pg_attrdef.adrelid = pg_class.oid
          AND   pg_attrdef.adnum = pg_attribute.attnum) AS def
        FROM pg_tables,
       pg_class
       JOIN pg_attribute
       ON pg_class.oid = pg_attribute.attrelid
       AND pg_attribute.attnum > 0
       LEFT JOIN pg_constraint
           ON pg_constraint.contype = \'p\'::"char"
           AND pg_constraint.conrelid = pg_class.oid
           AND (pg_attribute.attnum = ANY (pg_constraint.conkey))
        LEFT JOIN pg_constraint AS pc2
           ON pc2.contype = \'f\'::"char"
           AND pc2.conrelid = pg_class.oid
           AND (pg_attribute.attnum = ANY (pc2.conkey))
        WHERE pg_class.relname = pg_tables.tablename
        AND   pg_attribute.atttypid <> 0::OID
        and schemaname in ( 'public')
        and tablename = 'poisson'
       ORDER BY schemaname, tablename, field ASC)
        select * from req order by tablename, attnum

**Comment by quidoz** [comment]
Bonjour
    
    Je viens de tester vite fait ... la version sur le dépôt me semble
    avoir toujours le même problème.
    Et le script ne donne aucun enregistrement. 
    
    Je regarderai mieux demain matin
    
    A+
    
    MCQ
    
    
    
    Le 22/04/2020 à 09:35, Eric Quinton a
      écrit :
    
    
      Est-ce que tu as testé avec la version actuelle ? Il y a eu des
        modifs depuis la première version.
      Sinon, essaie d'exécuter ce script (c'est celui qui est
        exécuté, modifié à la marge pour intégrer manuellement le nom du
        schéma et de la table) :
        with req as
        (SELECT DISTINCT on (schemaname, tablename, field) schemaname,
        pg_tables.tablename,
        attnum, pg_attribute.attname AS field,
        format_type(pg_attribute.atttypid,NULL) AS "type",
        (SELECT
        col_description(pg_attribute.attrelid,pg_attribute.attnum)) AS
        COMMENT,
        CASE pg_attribute.attnotnull
        WHEN FALSE THEN 0
        ELSE 1
        END AS "notnull",
        pg_constraint.conname AS "key",
        pc2.conname AS ckey,
        (SELECT pg_attrdef.adsrc
        FROM pg_attrdef
        WHERE pg_attrdef.adrelid = pg_class.oid
        AND pg_attrdef.adnum = pg_attribute.attnum) AS def
        FROM pg_tables,
        pg_class
        JOIN pg_attribute
        ON pg_class.oid = pg_attribute.attrelid
        AND pg_attribute.attnum > 0
        LEFT JOIN pg_constraint
        ON pg_constraint.contype = 'p'::"char"
        AND pg_constraint.conrelid = pg_class.oid
        AND (pg_attribute.attnum = ANY (pg_constraint.conkey))
        LEFT JOIN pg_constraint AS pc2
        ON pc2.contype = 'f'::"char"
        AND pc2.conrelid = pg_class.oid
        AND (pg_attribute.attnum = ANY (pc2.conkey))
        WHERE pg_class.relname = pg_tables.tablename
        AND pg_attribute.atttypid <> 0::OID
        and schemaname in ( 'public')
        and tablename = 'poisson'
        ORDER BY schemaname, tablename, field ASC)
        select * from req order by tablename, attnum

**Comment by equinton** [comment]
Je n'arrive pas à reproduire le pb. J'ai créé la table, et la génération de la structure fonctionne correctement.
![Capture d’écran de 2020-04-24 09-11-35](https://user-images.githubusercontent.com/6715861/80184955-d1275700-860b-11ea-9146-fbc7ba883478.png)

Est-ce qu'une autre table espece existerait dans un autre schéma ? Cela pourrait être une piste de recherche.

**Comment by quidoz** [comment]
Bonjour
Le script ne me donne que le commentaire sur l'attribut cd_nom mais pas sur la table. Attention ce script ne marche plus en postgresql12 (la colonne pg_attrdef.adsrc n'existe plus dans la table pg_attrdef)

J'ai un petit souci avec ton dépôt. T'es sur qu'il contient la nouvelle version du logiciel ? il ne semble pas avoir été mis à jour récemment ?

**Comment by equinton** [comment]
Correction du script, qui fonctionne maintenant en v12.
Ajout d'un sommaire au format html
Peux-tu refaire un test avec la version actuelle ?
