### ISSUE TITLE
ajout de formats de sortie

### ISSUE THREAD

**Issue by quidoz** [equinton/dbstructure#2]
Bonjour

Dans la gestion au quotidien de mes bases de données, je souhaite ajouter dans chacune de mes bases de données un schéma "metadonnee" avec deux tables  (une pour décrire les tables et une pour décrire les attributs des tables -> ce qui me permettrait de construire le dictionnaire de donnée).  A noter que la table de métadonnée sur les tables n'est pas indispensable. 

Ces tables pourraient être construites avec les informations extraites de ce programme php + éventuellement une notion d'unité (NDR : je pensais faire un post traitement du champ commentaire de chaque variable car il n'y a pas de champ prévu pour dans sql et c'est normal)

Est ce qu'il serait "facile"' de faire une sortie SQL des informations qui sont dans le fichier html ?

**Comment by equinton** [comment]
Ajout d'un export au format csv, avec la possibilité d'extraire soit la liste des tables, soit la liste des colonnes
options: 
--format=csv
--csvtype=columns|tables
